<?php

/*********************************************************************
* Extension configuration file for ext "tx_skinDummy".
*
* Generated by ext 15-09-2013 17:40 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Gridelements Extended for flexible content elements',
  'description' => 'This extension provide some hooks to make flexible content elements easier with gridelements. We\'ve published a Yeoman generator to improve your development (watch documentation for more details)',
  'category' => 'plugin',
  'author' => 'Grégory Copin',
  'author_email' => 'gcopin@inouit.com',
  'author_company' => 'Inouit',
  'shy' => 0,
  'dependencies' => 'cms',
  'conflicts' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 1,
  'lockType' => '',
  'version' => '1.0.2',
  'constraints' =>
  array (
    'depends' =>
      array (
        'typo3' => '6.2.0-6.2.99',
        'php' => '5.3.0-0.0.0',
        'cms' => '1.1.0-0.0.0',
        'extbase' => '',
        'fluid' => '',
        'gridelements' => '2.0.2',
      ),
    'conflicts' =>
      array (
      ),
    'suggests' =>
      array (
      ),
  ),
  'suggests' =>
  array (
  ),
  'user' => 'gcopin',
  'comment' => '',
);

?>